devdog/board/urls.py
from django.urls import path
from board import views

app_name = 'board'

urlpatterns = [
    # path('article/',views.main, name='boardmain'),
    path('article/',views.read, name='read'),
    path('article/new/',views.create, name='create'),
    # path('article/create/<int:pagenum>/', views.create, name='create'),
    path('article/<int:article_id>/',views.detail, name='detail'),
    # path('article/<int:article_id>/new/'views.comment, name='comment'),
]

devdog/devdog/urls.py
from django.contrib import admin
from django.urls import path,include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('qna/', include('qna.urls')),
    path('user/', include('user.urls')),
    path('', views.main, name='main'),
]

devdog/qna/urls.py
from django.urls import path
from board import views


urlpatterns = [
    path('qna/',views.main, name='qnamain'),
]

devdog/user/urls.py
from django.urls import path,include
from user import views

app_name = 'user'

urlpatterns = [
    path('signup/',views.signup, name='signup'),
    path('signin/',views.signin, name='signin'),
    path('',include('django.contrib.auth.urls')),
]

devdog/board/models.py
from django.db import models
from user.models import CustomUser
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=15)
    user_id = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    time = models.DateTimeField(auto_now=True)
    content = models.TextField()

    def __str__(self):
        return self.title
        

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    text = models.TextField()
    def __str__(self):
        return self.text
    

devdog/main/models.py
from django.db import models

# Create your models here.

devdog/qna/models.py
from django.db import models
from user.models import CustomUser
# Create your models here.
class Question(models.Model):
    title = models.CharField(max_length=20)
    time = models.DateTimeField(auto_now=True)
    people = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    content = models.TextField()
    
    def __str__(self):
        return self.title

class Answer(models.Model):
    article_id = models.ForeignKey(Question, on_delete=models.CASCADE)
    user_id = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    content = models.TextField()
    
    def __str__(self):
        return self.content

devdog/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    student_id = models.CharField(max_length=9)

    def __str__(self):
        return self.username

devdog/board/forms.py
from django import forms
from .models import Article,Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

devdog/user/forms.py
from django import forms
from .models import CustomUser


class LoginForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username','password']


class UserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username','student_id','password']

devdog/board/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Article,Comment
from django.utils import timezone
from user.models import CustomUser
from .forms import ArticleForm,CommentForm
# from django.core.paginator import paginator

# Create your views here.
def main(request):
    return render(request, 'board/Notice.html')
def read(request):
    articles = Article.objects
    article_list = Article.objects.all()
    # paginator = Paginator(article_list, 10)
    # page = request.GET.get('page')
    return render(request, 'board/Notice.html',{'articles':articles})

def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid:
            post = form.save(commit=False)
            post.time = timezone.now()
            post.save()
            return redirect('../') 
    else:
        form = ArticleForm()
        return render(request, 'board/new.html', {'form':form})

def detail(request,article_id):
    article = get_object_or_404(Article, id=article_id)
    user = CustomUser.objects
    if request.user.is_authenticated:
        if request.method=='POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.author = request.user
                comment.text = form.cleaned_data["text"]
                comment.save()
                return redirect("board:detail", article_id)
        else:
            form = CommentForm()
            return render(request, 'board/Notice_detail.html', {'article':article,'form':form})
            

    

    

devdog/main/views.py
from django.shortcuts import render

def main(request):
    return render(request, 'main/main.html')

devdog/qna/views.py
from django.shortcuts import render

# Create your views here.

devdog/user/views.py
from django.shortcuts import render,redirect
from .forms import UserForm,LoginForm
from .models import CustomUser
from django.contrib.auth import login,authenticate
from django.http import HttpResponse

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = CustomUser.objects.create_user(username=form.cleaned_data["username"],password=form.cleaned_data["password"],student_id=form.cleaned_data["student_id"])
            login(request, new_user)
            return redirect('../../')
    else:
        form = UserForm()
        return render(request, 'user/sign_up.html', {'form':form})

# Create your views here.
def signin(request):
    if request.method == "POST":
        form = LoginForm (request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username= username, password= password)

        if user is not None:
            login(request,user)
            return redirect('../../')
        else:
            return HttpResponse('로그인 실패 다시 시도해보세요.')
    else:
        form = LoginForm()
        return render(request, 'user/sign_in.html',{'form':form})

devdog/board/templates/board/Notice.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>개발자들 공지</title>

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/dogdevelop.jpg' %}">

    <link rel="stylesheet" href="{% static 'css/Notice.css' %}">

    <script type="text/javascript" src="{% static 'js/Notice.js' %}"></script>
  </head>
  <body>
    <!--  접근 시 필요한 클래스 명

    ad 상단 광고창

    ntcNo 공지글의 번호 (몇 번째 글인가)
    noticeTitle 공지글의 제목
    ntcNick 작성자, ntcDate 작성일자

    pageNum 밑에 페이지 숫자

    cb1_1~3 콘텐츠 사이드 배너

    intro1~n 하나의 정보 블럭?

    -->

    <section id="main">
      <div class="intro1">
        <div class="ad">
          <img src="{% static 'img/adimg.png' %}" alt="">
        </div>
      </div>

      <div class="intro2">
        <a href="{% url 'board:create' %}" >글쓰기</a>
        <div class="content">
          <h1 class="contentTitle">공지사항</h1>
          <div class="noticeBoard">
            <ul>
              {% for article in articles.all %}
              <li><p><span class="ntcNo">{{article.id}}</span><a href="{% url 'board:detail' article.id  %}"><span class="noticeTitle">{{article.title}}</span></a><span class="ntcDate">01-18</span><span class="ntcNick">{{article.user_id}}</span></p></li>
              {% endfor %}
            </ul>
          </div>

          <div class="pageNum">
            <span><a href="#"><</a></span>
            
            <a href="#" style="color:rgb(285,165,122); font-weight:bold;">1</a>
            <a href="#">2</a>
            <span><a href="#">></a></span>
          </div>
        </div>

        <div class="contentBanner">

          <div class="cb1">
            <div class="cb1Img">
              <ul>
                <li class="cb1_1"><a target="_blank" href="https://www.notion.so/Python-5cf6d6da3f1e4195b8d2b4be6736ce22"><img src="{% static 'img/파이썬.png' %}" alt=""></a>파이썬 강의 자료</li>
                <li class="cb1_2"><a target="_blank" href="https://youtu.be/Jos_gkCP-4w"><img src="{% static 'img/워다타.jpg' %}" alt=""></a>워다타 알아보기</li>
                <li class="cb1_3"><a target="_blank" href="https://slack.com/intl/en-kr/"><img src="{% static 'img/슬랙.png'%}" alt=""></a>슬랙 바로가기</li>
              </ul>
            </div>
            <button class="cbLeft" onclick="contentBannerLeft()"><</button><button class="cbRight" onclick="contentBannerRight()">></button>
          </div>

          <div class="cb2">
            개발자들 알림
          </div>
        </div>

      </div>

      <div class="intro3">

      </div>
      <div class="intro4">
        <div class="introfooter">
          <footer id="footer">
            <fieldset class="infoForm">
              <a href="#">이용약관</a>
              <span class="bar">|</span>
              <a href="#"><strong>개인정보처리방침</strong></a>
              <span class="bar">|</span>
              <a href="#">고객센터</a>
            </fieldset>

            <div class="copyright">
              Copyright © SKHU <span>DogDevelop-Fish-bread-Team.</span> All right Reserved.
            </div>
          </footer>
        </div>
      </div>


    </section>


  </body>
</html>

devdog/board/templates/board/Notice_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>개발자들 공지</title>

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/dogdevelop.jpg' %}">

    <link rel="stylesheet" href="{% static 'css/Notice_detail.css' %}">

    <script type="text/javascript" src="{% static 'js/Notice_detail.js' %}"></script>
  </head>
  <body>
    <!--  접근 시 필요한 클래스 명

    ntcTitle 공지사항 제목
    ntcInfo 공지글의 정보 >>> ntcNick 작성자, ntcDate 작성일자
    ntcText 공지사항 글(내용)

    BackText 이전글
    NextText 다음글

    cb1_1~3 콘텐츠 사이드 배너

    intro1~n 하나의 정보 블럭?

    -->

    <header id="header">
      <nav id="banner">
        <h1><a href="../main/Main.html">개발자들</a></h1>
        <div class="bannerMenu">
          <ul class="menu">
            <li><a href="../notice/Notice.html"><b>공지</b></a></li>
            <li><a href="#"><b>소개</b></a></li>
            <li><a href="#"><b>QnA</b></a></li>
            <li><a href="#"><b>Slack</b></a></li>
          </ul>
        </div>

        <div class="sign">
          <ul class="signMenu">
            <li><a target="_blank" href="../signin/sign_in.html"><b>로그인</b></a></li>
            <li><a target="_blank" href="../signup/sign_up.html"><b>가입하기</b></a></li>
          </ul>
        </div>
      </nav>
    </header>

    <section id="main">
      <div class="intro1">
        <div class="ad">
          <img src="{% static 'img/adimg.png' %}" alt="">
        </div>
      </div>

      <div class="intro2">
        <div class="content">
          <h1 class="contentTitle">공지사항 <span><a class="goNtcList" href="{% url 'board:read' %}">목록</a></span></h1>

          <p class="ntcTitle"><span>{{ article.title }}</span></p>

          <p class="ntcInfo"><span class="ntcNick">{{article.user_id}}</span><span class="ntcDate">2020-01-18</span></p>

          <div class="ntc">
            <div class="ntcText">
              {{ article.content }}
            </div>
          
          <div class="ntc">
            <form method="POST">
              {% csrf_token %}
              <table>
                  {{form.as_table}}
              </table>
              <input type="submit" value="댓글달기">
          </form>
            {% for comment in article.comments.all %}
            {{ comment.content_c }}
            {% endfor %}
          </div>
          

            <div class="ntcBack">
              <div class="BackText">
                이전글 - 이전글이 없습니다.
              </div>
            </div>

            <div class="ntcNext">
              <div class="NextText">
                <a href="#">다음글</a> - <a href="#">개발자들 8차 정기모임 공지</a>
              </div>
            </div>
          </div>
        </div>

        <div class="contentBanner">

          <div class="cb1">
            <div class="cb1Img">
              <ul>
                <li class="cb1_1"><a target="_blank" href="https://www.notion.so/Python-5cf6d6da3f1e4195b8d2b4be6736ce22"><img src="{% static 'img/파이썬.png' %}" alt=""></a>파이썬 강의 자료</li>
              </ul>
            </div>
            <button class="cbLeft" onclick="contentBannerLeft()"><</button><button class="cbRight" onclick="contentBannerRight()">></button>
          </div>

          <div class="cb2">
            개발자들 알림
          </div>
        </div>

      </div>

      <div class="intro3">

      </div>
<br>
<br>
      <div class="intro4">
        <div class="introfooter">
          <footer id="footer">
            <fieldset class="infoForm">
              <a href="#">이용약관</a>
              <span class="bar">|</span>
              <a href="#"><strong>개인정보처리방침</strong></a>
              <span class="bar">|</span>
              <a href="#">고객센터</a>
            </fieldset>

            <div class="copyright">
              Copyright © SKHU <span>DogDevelop-Fish-bread-Team.</span> All right Reserved.
            </div>
          </footer>
        </div>
      </div>


    </section>


  </body>
</html>

devdog/board/templates/board/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>개발자들 공지</title>

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/dogdevelop.jpg' %}">

    <link rel="stylesheet" href="{% static 'css/Notice.css' %}">

    <script type="text/javascript" src="{% static 'js/Notice.js' %}"></script>
  </head>
  <body>
    <!--  접근 시 필요한 클래스 명

    ad 상단 광고창

    ntcNo 공지글의 번호 (몇 번째 글인가)
    noticeTitle 공지글의 제목
    ntcNick 작성자, ntcDate 작성일자

    pageNum 밑에 페이지 숫자

    cb1_1~3 콘텐츠 사이드 배너

    intro1~n 하나의 정보 블럭?

    -->

    <section id="main">
      <div class="intro1">
        <div class="ad">
          <img src="{% static 'img/adimg.png' %}" alt="">
        </div>
      </div>

      <div class="intro2">
        <div class="content">
          {% block content %}
          {% endblock content %}
        </div>

        <div class="contentBanner">

          <div class="cb1">
            <div class="cb1Img">
              <ul>
                <li class="cb1_1"><a target="_blank" href="https://www.notion.so/Python-5cf6d6da3f1e4195b8d2b4be6736ce22"><img src="{% static 'img/파이썬.png' %}" alt=""></a>파이썬 강의 자료</li>
                <li class="cb1_2"><a target="_blank" href="https://youtu.be/Jos_gkCP-4w"><img src="{% static 'img/워다타.jpg' %}" alt=""></a>워다타 알아보기</li>
                <li class="cb1_3"><a target="_blank" href="https://slack.com/intl/en-kr/"><img src="{% static 'img/슬랙.png'%}" alt=""></a>슬랙 바로가기</li>
              </ul>
            </div>
            <button class="cbLeft" onclick="contentBannerLeft()"><</button><button class="cbRight" onclick="contentBannerRight()">></button>
          </div>

          <div class="cb2">
            개발자들 알림
          </div>
        </div>

      </div>

      <div class="intro3">

      </div>
      <div class="intro4">
        <div class="introfooter">
          <footer id="footer">
            <fieldset class="infoForm">
              <a href="#">이용약관</a>
              <span class="bar">|</span>
              <a href="#"><strong>개인정보처리방침</strong></a>
              <span class="bar">|</span>
              <a href="#">고객센터</a>
            </fieldset>

            <div class="copyright">
              Copyright © SKHU <span>DogDevelop-Fish-bread-Team.</span> All right Reserved.
            </div>
          </footer>
        </div>
      </div>


    </section>


  </body>
</html>

devdog/board/templates/board/new.html
{% extends 'board/base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="제출하기">
    </form>
{% endblock %}

devdog/main/templates/main/Main.html
{% extends 'main/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>개발자들</title>

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/dogdevelop.jpg' %}">

    <link rel="stylesheet" href="{% static 'css/Main.css'%}">

    <script type="text/javascript" src="{% static 'js/Main.js' %}"></script>

    <!--  Main.html  // 메인 화면

    intro1~n 하나의 정보 블럭?

    -->
  </head>
  <body id="wrap">



    <section id="main">
      <div class="intro1">
        <div class="intro1Content">
          <img src="{% static 'img/개들홈페이지.png' %}" alt="">
        </div>
      </div>

      <div class="intro2">
        <br><br><br><br><br><br>
        <span class="intro2H">개발자들 강의 자료</span><br><br>
        <span class="intro2SH">동아리 모임 때 진행했던 강의 자료 및 참고자료를 확인할 수 있습니다.</span><br><br><br>

        <div class="lecture">
          <a class="lecture1" target="_blank" href="https://www.notion.so/Python-5cf6d6da3f1e4195b8d2b4be6736ce22">
            <div class="lect1">
              <img class="lectImg" src="{% static 'img/파이썬.png' %}" alt=""><br><br><br><span>개발자들을 위한<br>파이썬 강의</span><br><br>이한길 제작<br><br><br>
            </div>
          </a>

          <a class="lecture2" href="#">
            <div class="lect2">
              <img class="lectImg" src="{% static 'img/c언어.png' %}" alt=""><br><br><br><span>개발자들을 위한<br>C언어 강의</span><br><br>제작 중<br><br><br>
            </div>
          </a>

          <a class="lecture3" href="#">
            <div class="lect3">
              <img class="lectImg" src="{% static 'img/html.png' %}" alt=""><br><br><br><span>개발자들을 위한<br>웹 개발 강의</span><br><br>제작 중<br><br><br>
            </div>
          </a>
        </div>
      </div>


      <div class="intro3">
        <br>
        홈페이지 기능 소개 <br><br>
        개발자들 강의 자료를 열람할 수 있다.<br><br>
        개발자들의 공지사항을 쉽게 볼 수 있다.<br>------미완성--------
      </div>

      <div class="intro4">
        <br><br><br>
        워다타 소개 (광고 배너 처럼 무엇을 알리기 위해)<br><br><br>
        <b>2019 성공회대학교 창업경진대회 최우수상</b><br>------미완성--------<br><br><br><br>
        <img src="{% static 'img/워다타.jpg' %}" alt="">
      </div>



      <div class="introfooter">
        <footer id="footer">
          <fieldset class="infoForm">
            <a href="#">이용약관</a>
            <span class="bar">|</span>
            <a href="#"><strong>개인정보처리방침</strong></a>
            <span class="bar">|</span>
            <a href="#">고객센터</a>
          </fieldset>

          <div class="copyright">
            Copyright © SKHU <span>DogDevelop-Fish-bread-Team.</span> All right Reserved.
          </div>
        </footer>
      </div>
    </section>

  </body>

</html>

devdog/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>개발자들</title>

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/dogdevelop.jpg' %}">

    <link rel="stylesheet" href="{% static 'css/Main.css'%}">

    <script type="text/javascript" src="{% static 'js/Main.js' %}"></script>

    <!--  Main.html  // 메인 화면

    intro1~n 하나의 정보 블럭?

    -->
  </head>
  <body id="wrap">

<header id="header">
    <nav id="banner">
      <h1><a href="../main/Main.html">개발자들</a></h1>
      <div class="bannerMenu">
        <ul class="menu">
          <li><a href="{% url 'board:read' %}"><b>공지</b></a></li>
          <li><a href="#"><b>소개</b></a></li>
          <li><a href="#"><b>QnA</b></a></li>
          <li><a href="#"><b>Slack</b></a></li>
        </ul>
      </div>
      {% if user.is_authenticated %}
      <div class="sign">
        <ul class="signMenu">
          <li><a target="_blank"><b>환영합니다 {{user.username}}</b></a></li>
          <li><a target="_blank" href="{% url 'user:logout' %}"><b>logout</b></a></li>

        </ul>
      </div>
      {% else %}
      <div class="sign">
        <ul class="signMenu">
          <li><a target="_blank" href="{% url 'user:signin' %}"><b>로그인</b></a></li>
          <li><a target="_blank" href="{% url 'user:signup' %}"><b>가입하기</b></a></li>
        </ul>
      </div>
      {% endif %}
    </nav>
</header>
{% block content %}


    <section id="main">
      <div class="intro1">
        <div class="intro1Content">
          <img src="{% static 'img/개들홈페이지.png' %}" alt="">
        </div>
      </div>

      <div class="intro2">
        <br><br><br><br><br><br>
        <span class="intro2H">개발자들 강의 자료</span><br><br>
        <span class="intro2SH">동아리 모임 때 진행했던 강의 자료 및 참고자료를 확인할 수 있습니다.</span><br><br><br>

        <div class="lecture">
          <a class="lecture1" target="_blank" href="https://www.notion.so/Python-5cf6d6da3f1e4195b8d2b4be6736ce22">
            <div class="lect1">
              <img class="lectImg" src="{% static 'img/파이썬.png' %}" alt=""><br><br><br><span>개발자들을 위한<br>파이썬 강의</span><br><br>이한길 제작<br><br><br>
            </div>
          </a>

          <a class="lecture2" href="#">
            <div class="lect2">
              <img class="lectImg" src="{% static 'img/c언어.png' %}" alt=""><br><br><br><span>개발자들을 위한<br>C언어 강의</span><br><br>제작 중<br><br><br>
            </div>
          </a>

          <a class="lecture3" href="#">
            <div class="lect3">
              <img class="lectImg" src="{% static 'img/html.png' %}" alt=""><br><br><br><span>개발자들을 위한<br>웹 개발 강의</span><br><br>제작 중<br><br><br>
            </div>
          </a>
        </div>
      </div>


      <div class="intro3">
        <br>
        홈페이지 기능 소개 <br><br>
        개발자들 강의 자료를 열람할 수 있다.<br><br>
        개발자들의 공지사항을 쉽게 볼 수 있다.<br>------미완성--------
      </div>

      <div class="intro4">
        <br><br><br>
        워다타 소개 (광고 배너 처럼 무엇을 알리기 위해)<br><br><br>
        <b>2019 성공회대학교 창업경진대회 최우수상</b><br>------미완성--------<br><br><br><br>
        <img src="{% static 'img/워다타.jpg' %}" alt="">
      </div>
{% endblock %}


      <div class="introfooter">
        <footer id="footer">
          <fieldset class="infoForm">
            <a href="#">이용약관</a>
            <span class="bar">|</span>
            <a href="#"><strong>개인정보처리방침</strong></a>
            <span class="bar">|</span>
            <a href="#">고객센터</a>
          </fieldset>

          <div class="copyright">
            Copyright © SKHU <span>DogDevelop-Fish-bread-Team.</span> All right Reserved.
          </div>
        </footer>
      </div>
    </section>

  </body>

</html>

devdog/user/templates/user/sign_in.html
<h2>login</h2>
<form method="POST" action="">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">로그인하기</button>
    <a href = "{% url 'user:signup' %}">회원가입</a>
</form>

devdog/user/templates/user/sign_up.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>개발자들 : 회원가입</title>

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/dogdevelop.jpg' %}">

    <link rel="stylesheet" href="{% static 'css/sign_up.css' %}">

    <script type="text/javascript" src="{% static 'js/sign_up.js' %}"></script>

    <!--

    id 아이디 입력 박스
    pw 비밀번호 입력 박스
    repw 비밀번호 재입력 박스
    name 이름 입력 박스
    _class 학번 입력 박스


  -->
  </head>
  <body id="wrap">
    <header id="logo">
      <h1 class="logo"><a href="../main/Main.html">개발자들</a></h1>
    </header>

    
      <form  action="" method="POST">
        {% csrf_token %}
        
          {{ form.as_p }}
        
          <input class="signupBtn" type="submit" name="" value="가입하기" onclick="inputTF()">
      </form>
    

    <footer id="footer">
      <fieldset class="infoForm">
        <a href="#">이용약관</a>
        <span class="bar">|</span>
        <a href="#"><strong>개인정보처리방침</strong></a>
        <span class="bar">|</span>
        <a href="#">고객센터</a>
      </fieldset>

      <div class="copyright">
        Copyright © SKHU <span>DogDevelop-Fish-bread-Team.</span> All right Reserved.
      </div>
    </footer>
  </body>
</html>